name: mazifer
description: A <5kb Flutter app that turns any word into a maze!

author: Zvi Karp <zvi@zektec.com>

version: 1.0.0
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.12.0
  cupertino_icons: ^0.1.2
  esys_flutter_share: ^0.0.9
  flutter_launcher_icons: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
   - assets/images/a.svg
   - assets/images/b.svg
   - assets/images/c.svg
   - assets/images/d.svg
   - assets/images/e.svg
   - assets/images/f.svg
   - assets/images/g.svg
   - assets/images/h.svg
   - assets/images/i.svg
   - assets/images/j.svg
   - assets/images/k.svg
   - assets/images/l.svg
   - assets/images/m.svg
   - assets/images/n.svg
   - assets/images/o.svg
   - assets/images/p.svg
   - assets/images/q.svg
   - assets/images/r.svg
   - assets/images/s.svg
   - assets/images/t.svg
   - assets/images/u.svg
   - assets/images/v.svg
   - assets/images/w.svg
   - assets/images/x.svg
   - assets/images/y.svg
   - assets/images/z.svg
   - assets/images/[.svg
   - assets/images/].svg
   - assets/images/+.svg

  
  fonts:
    - family: Yanone
      fonts:
        - asset: assets/fonts/YanoneKaffeesatz-Regular.ttf